package com.arashrahimi46.iptv.mobile.data.repository

import android.content.Context
import com.arashrahimi46.iptv.mobile.data.db.AppDatabase
import com.arashrahimi46.iptv.mobile.data.model.Channel
import com.arashrahimi46.iptv.mobile.data.model.ContentType
import com.arashrahimi46.iptv.mobile.data.model.Favorite
import com.arashrahimi46.iptv.mobile.data.model.VodTitle
import com.arashrahimi46.iptv.mobile.data.settings.UserSettings
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flatMapLatest
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.withContext

/**
 * Wraps [com.arashrahimi46.iptv.mobile.data.db.FavoriteDao] behind a small surface
 * shared by every screen that shows a favorite-toggle affordance (Live,
 * Movies, Series, Search, Detail, and the real Favorites screen itself) so
 * the toggle/insert/delete logic lives in one place instead of being
 * duplicated per-ViewModel. All writes run on [Dispatchers.IO], matching
 * [PlaylistRepositoryImpl]'s pattern.
 *
 * Favorites are stored keyed by each item's *stable* identity ([Favorite.streamKey]),
 * not by its autogenerated Room row id (which is re-assigned on every re-import). Callers
 * still pass row ids -- the row is loaded once to compute its stable key -- and membership
 * is exposed as the set of *current* row ids in the active source, so no consumer screen
 * needs to know about the keying change. See [Favorite] for why row ids can't be trusted.
 */
@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)
class FavoritesRepository(context: Context) {
    private val db = AppDatabase.get(context)
    private val dao = db.favoriteDao()
    private val channelDao = db.channelDao()
    private val vodDao = db.vodTitleDao()
    private val settings = UserSettings(context)

    /** Real-time set of favorited channel row ids in the active source -- cheap membership checks for tile favorite icons. */
    val favoriteChannelIds: Flow<Set<Long>> = settings.activeSourceId.flatMapLatest { sid ->
        if (sid == null) flowOf(emptySet()) else dao.observeFavoriteChannelIdsInSource(sid).map { it.toSet() }
    }

    /** Real-time set of favorited VOD title row ids (movies + series) in the active source. */
    val favoriteVodIds: Flow<Set<Long>> = settings.activeSourceId.flatMapLatest { sid ->
        if (sid == null) flowOf(emptySet()) else dao.observeFavoriteVodIdsInSource(sid).map { it.toSet() }
    }

    fun observeAll(): Flow<List<Favorite>> = dao.observeAll()

    /** Resolve favorited channel keys to the active source's current channel rows (unresolvable ones are dropped). */
    suspend fun channelsByKeys(sourceId: Long, keys: List<String>): List<Channel> =
        if (keys.isEmpty()) emptyList() else channelDao.channelsByFavoriteKeys(sourceId, keys)

    /** Resolve favorited VOD keys to the active source's current title rows (unresolvable ones are dropped). */
    suspend fun titlesByKeys(sourceId: Long, keys: List<String>): List<VodTitle> =
        if (keys.isEmpty()) emptyList() else vodDao.titlesByFavoriteKeys(sourceId, keys)

    suspend fun toggleChannel(channelId: Long): Unit = withContext(Dispatchers.IO) {
        val channel = channelDao.getById(channelId) ?: return@withContext
        val key = channelKey(channel)
        if (dao.countByKey(ContentType.LIVE, key) > 0) {
            dao.deleteByKey(ContentType.LIVE, key)
        } else {
            dao.insert(Favorite(contentType = ContentType.LIVE, streamKey = key))
        }
    }

    /** [contentType] should be MOVIE or SERIES, matching the [VodTitle.isSeries] flag. */
    suspend fun toggleVod(vodTitleId: Long, contentType: ContentType): Unit = withContext(Dispatchers.IO) {
        val title = vodDao.getById(vodTitleId) ?: return@withContext
        val key = vodKey(title)
        if (dao.countByKey(contentType, key) > 0) {
            dao.deleteByKey(contentType, key)
        } else {
            dao.insert(Favorite(contentType = contentType, streamKey = key))
        }
    }

    companion object {
        // Stable-key priority: "externalId|name" (Xtream/tvg-id, truly stable, combined with name to
        // disambiguate) -> name -> streamUrl. name is preferred over streamUrl because many providers
        // hand out a rotating session token/port/host in the URL, so streamUrl differs on every
        // re-import and the favorite would silently drop; name is far more stable. name is non-null on
        // both entities, so streamUrl is a formal tail only reached if name were ever blank.
        //
        // externalId is concatenated with name rather than used alone: some providers reuse one
        // externalId/tvg-id across several distinctly-named rows (e.g. regional affiliates sharing an
        // EPG id -- "10 Comedy -- Sydney/Melbourne/Brisbane/..."), which used to collapse every one of
        // those rows onto the same favorites key -- toggling the heart on one favorited (and displayed
        // as favorited) all of them. MUST match FavoriteDao's COALESCE(externalId || '|' || name, name, streamUrl).

        /** MUST match FavoriteDao's `COALESCE(externalId || '|' || name, name, streamUrl)` channel-key expression. */
        fun channelKey(channel: Channel): String = channel.externalId?.let { "$it|${channel.name}" } ?: channel.name

        /** MUST match FavoriteDao's `COALESCE(externalId || '|' || name, name, streamUrl)` VOD-key expression. */
        fun vodKey(title: VodTitle): String = title.externalId?.let { "$it|${title.name}" } ?: title.name
    }
}
